### ISSUE TITLE
corrupt jarfile

### ISSUE THREAD

**Issue by bjt-user** [lalyos/jfiglet#25]
After trying to use jfiglet from maven central like described in the `README.md`
```
curl -o jfiglet.jar http://central.maven.org/maven2/com/github/lalyos/jfiglet/0.0.8/jfiglet-0.0.8.jar
java -jar jfiglet.jar "text to convert"
```
I get the following error:
```
Error: Invalid or corrupt jarfile jfiglet.jar
```

the `jar` file is present:
```
-rw-r--r--. 1 me mygroup 2522 Oct  5 11:23 jfiglet.jar
```
but seems to be invalid:
```
$ jar -tf jfiglet.jar 
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
	at jdk.jartool/sun.tools.jar.Main.list(Main.java:1502)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:361)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1683)
```

Maybe the link is not correct?

**Comment by lalyos** [comment]
Seems like the central maven repo is down ... even more DNS is missing:
```
curl http://central.maven.org/
curl: (6) Could not resolve host: central.maven.org
```

**Comment by lalyos** [comment]
looks like they had some issues in the last couple of days: https://status.maven.org/

**Comment by lalyos** [comment]
New url is updated in readme
