### ISSUE TITLE
ArrayIndexOutOfBoundsException some flf fonts

### ISSUE THREAD

**Issue by Kieaer** [lalyos/jfiglet#30]
```
C:\Users\cloud\IdeaProjects\Essentials\Essential\src\main\resources\font>java -jar jfiglet.jar -f hanglg16.flf "text to
convert"
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 8481 out of bounds for length 1024
        at com.github.lalyos.jfiglet.FigletFont.<init>(FigletFont.java:153)
        at com.github.lalyos.jfiglet.FigletFont.convertOneLine(FigletFont.java:195)
        at com.github.lalyos.jfiglet.FigletFont.convertOneLine(FigletFont.java:215)
        at com.github.lalyos.jfiglet.JFiglet.main(JFiglet.java:39)
```

flf font link: https://github.com/cmatsuoka/figlet-fonts/tree/master/cjkfonts
all flf fonts

**Comment by Kieaer** [comment]
I changed MAX_CHARS to 80000
but next error

English is ok, but korean/chinese/japanese is not working
```
Exception in thread "main" java.lang.NullPointerException: Cannot load from object array because "char2" is null
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.Smushing.addChar(Smushing.java:79)
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.Smushing.convert(Smushing.java:59)
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.FigletFont.convert(FigletFont.java:185)
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.FigletFont.convertOneLine(FigletFont.java:195)
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.FigletFont.convertOneLine(FigletFont.java:215)
	at com.github.lalyos.jfiglet/com.github.lalyos.jfiglet.JFiglet.main(JFiglet.java:39)
```
